language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    # Test nightly feature
    - rust: nightly
      env: NAME="nightly feature"
      script: cargo test --features nightly
    # Test MSRV
    - rust: 1.13.0
      env: NAME="MSRV test"
      script: cargo test --no-default-features --features std
    # Test if crate can be truly built without std
    # Disabled because this tooling started to error, feel free to fix it
    #- rust: nightly
    #  env: TARGET=thumbv7em-none-eabi
    #  script: xargo build --no-default-features --target $TARGET
    #  install:
    #    - cargo install xargo || true
    #    - rustup target install armv7-unknown-linux-gnueabihf
    #    - rustup component add rust-src

script:
  - cargo test && cargo test --no-default-features &&
    cargo test --no-default-features --features std &&
    cargo test --no-default-features --features "std i128"

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots

cache:
  directories:
    - /home/travis/.cargo
